from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
      migrations.CreateModel(name='Product',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=160)),('slug',models.SlugField(unique=True)),('category',models.CharField(max_length=80)),('description',models.TextField()),('price',models.DecimalField(decimal_places=2,max_digits=10)),('stock',models.PositiveIntegerField(default=0)),('image_url',models.URLField(blank=True)),('is_active',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True))]),
      migrations.CreateModel(name='Order',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('full_name',models.CharField(max_length=120)),('email',models.EmailField(max_length=254)),('phone',models.CharField(max_length=20)),('address',models.TextField()),('city',models.CharField(max_length=80)),('pincode',models.CharField(max_length=12)),('total_amount',models.DecimalField(decimal_places=2,max_digits=10)),('status',models.CharField(choices=[('PLACED','Placed'),('PROCESSING','Processing'),('SHIPPED','Shipped'),('DELIVERED','Delivered'),('CANCELLED','Cancelled')],default='PLACED',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='orders',to=settings.AUTH_USER_MODEL))]),
      migrations.CreateModel(name='OrderItem',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('product_name',models.CharField(max_length=160)),('price',models.DecimalField(decimal_places=2,max_digits=10)),('quantity',models.PositiveIntegerField()),('order',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='items',to='store.order')),('product',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='store.product'))])]
